### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jhpratt** [buffdb/buffdb#11]
- [ ] Successful test execution without `#[serial]` (currently needed due to multiple independent database connections)
- [ ] Convert remaining RPC services and associated tests to streaming
- [ ] Benchmarks (#2)
- [ ] Documentation
- [ ] iOS & Android clients
